CFLAGS=`{pkg-config --cflags grits}
LDFLAGS=`{pkg-config --libs grits}
LIB=teapot.so
default:V: $LIB
%.so: %.o
	gcc $CFLAGS -fPIC -shared -o $target $prereq $LDFLAGS
%.o: %.c
	gcc $CFLAGS -fPIC -c -o $target $prereq
clean:V:
	rm -f *.o *.so
install:V:
	cp $LIB /usr/lib/grits0/
uninstall:V:
	rm /usr/lib/grits0/$LIB
